### ISSUE TITLE
Can't get a connection to the GSA webinterface

### ISSUE THREAD

**Issue by schneemass** [martinboller/gse#9]
Hello,
i tried to install-GSE-2021.sh today on a fresh debain 11. But I can't get a connection to the GSA webinterface. Do I need to run another script if I want to use it as a standalone GSE?

LG 
Fred

**Comment by martinboller** [comment]
Hi Fred,
The Web interface should be available at https://hostname - if it isn't, check the status of gsad (systemctl status gsad.service) and nginx.service.

For the secondary server, there's no GSA installed, so you can only communicate through ospd-openvas.

If it still doesn't work, please provide details on the output from systemctl and/or journalctl
